backend:
  name: github
  repo:  gustavoespindola/basico # Path to your Github repository
  branch: master # Branch to update (master by default)
media_folder: "img/uploads" # Folder where user uploaded files should go
publish_mode: editorial_workflow
collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "site/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Headline", name: "projectheadline", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Thumbnail", name: "projectthumb", widget: "string"}
  - name: "pages"
    label: "Pages"
    folder: "site/content/pages" # The path to the folder where the documents are stored
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Layout", name: "layout", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
